### ISSUE TITLE
[BUG] [DOCUMENTATION] Documentation processing fails (v 0.2.3)

### ISSUE THREAD

**Issue by szymon-datalions** [szymon-datalions/pyinterpolate#130]
**Package version**
Documentation for the v 0.2.3 falls.

**Describe the bug**
```
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 24 source files that are out of date
updating environment: 24 added, 0 changed, 0 removed
reading sources... [  4%] code_documentation
reading sources... [  8%] code_documentation/distance

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 1021, in parse
    rststring, resources = exporter.from_notebook_node(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 840, in from_notebook_node
    nb, resources, **kw)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 384, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/jinja2/environment.py", line 1289, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/jinja2/environment.py", line 924, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 124, in top-level template code
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/share/jupyter/nbconvert/templates/rst/index.rst.j2", line 1, in top-level template code
    {%- extends 'display_priority.j2' -%}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/share/jupyter/nbconvert/templates/base/display_priority.j2", line 1, in top-level template code
    {%- extends 'base/null.j2' -%}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/share/jupyter/nbconvert/templates/base/null.j2", line 26, in top-level template code
    {%- block body -%}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/share/jupyter/nbconvert/templates/base/null.j2", line 29, in block 'body'
    {%- block body_loop -%}
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/share/jupyter/nbconvert/templates/base/null.j2", line 31, in block 'body_loop'
    {%- block any_cell scoped -%}
  File "<template>", line 17, in block 'any_cell'
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/share/jupyter/nbconvert/templates/base/null.j2", line 84, in block 'any_cell'
    {%- block markdowncell scoped-%} {%- endblock markdowncell -%}
  File "<template>", line 153, in block 'markdowncell'
jinja2.exceptions.UndefinedError: 'nbformat.notebooknode.NotebookNode object' has no attribute 'tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyinterpolate/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 1032, in parse
    str(e))
nbsphinx.NotebookError: UndefinedError in code_documentation/distance.ipynb:
'nbformat.notebooknode.NotebookNode object' has no attribute 'tags'

Notebook error:
UndefinedError in code_documentation/distance.ipynb:
'nbformat.notebooknode.NotebookNode object' has no attribute 'tags'
```

**To Reproduce**
1. Build documentation from Read The Docs service.

**Input Data Schema**
n/a

**Expected behavior**
Notebooks converted to the HTML files.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**
Previous run of documentation worked fine - I must compare those notebooks to the new ones...

**Comment by szymon-datalions** [comment]
Bug related to the version of **nbconvert** package
